import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from './context/AuthContext';
import Navbar from "./components/Navbar";
import Image from "next/image";
import background from './asset/65d5bfa43c1e3f4eee92efd4_65ced355bb7642d3cbd8fc5c-a5c83c114fa5e7903a67ef0168f6f9d0.jpeg'
import Providers from './components/Providers'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AuthProvider>
            {/* <Navbar /> */}
            <Image src={background} alt="background" className="absolute inset-0 w-full h-full object-cover brightness-50 blur-lg" />
            {children}
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
